<?php

/**
 * Implements hook_permission().
 */
function sparql_views_test_permission() {
  return array(
    'sparql_views_test test permission' => array(
      'title' => t('Test permission'),
      'description' => t('sparql_views_test test permission'),
    ),
  );
}

/**
 * Implements hook_views_api().
 */
function sparql_views_test_views_api() {
  return array(
    'api' => '3.0-alpha1',
  );
}

/**
 * Implements hook_views_data()
 */
function sparql_views_test_views_data() {
  return variable_get('sparql_views_test_views_data', array());
}

/**
 * Implements hook_views_plugins()
 */
function sparql_views_test_views_plugins() {
  return variable_get('sparql_views_test_views_plugins', array());
}